# Generated by Django 4.1.7 on 2023-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_app', '0002_alter_leavereportstudent_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stuffs',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
